### ISSUE TITLE
Rename extension

### ISSUE THREAD

**Issue by dktapps** [pmmp/pthreads#112]
As of 5.0.0, this extension now has an API that differs quite a bit from `pthreads`. It's also more performant and is easier to understand.

Since we don't actually have a claim to the name `pthreads` (this is an unofficial fork), we can't publish the extension to PECL under the `pthreads` name, and calling it `pthreads` is possibly misleading. We also can't submit official stubs to [jetbrains/phpstorm-stubs](https://github.com/jetbrains/phpstorm-stubs), requiring users to install custom stubs for IDE development.

I plan to release 6.0.0 soon, with some class renames and namespacing to distinguish it from `pthreads`.

Some possible new names (with the help of PM #internals-dev and ChatGPT):
- `pmthreads` - the obvious one, but brings up results for [Persistent Memory Threads](https://pure.manchester.ac.uk/ws/portalfiles/portal/162076150/PMThreads_PLDI2020_authorversion.pdf)
- `ptx`
- `pthreads-ng` - the original codename for v5 before release
- `pmmpthreads` - most verbose, but doesn't conflict with any known project, and is clear about origins

**Comment by SOF3** [comment]
`pmmpthreads` sounds fine to me. A bit long, but it's not namespaced anyway so users don't need to type it anywhere other than during installation or dependency declaration, and internally we just call it "threading" either way

**Comment by dktapps** [comment]
For consistency with our other projects, I chose a namespace of `pmmp\thread`. `pmmpthread` without the `s` works with this too, I think.

For some reason I instinctively `pmmpthreads` as "pmm pthreads", while `pmmpthread` reads as "pmmp thread".
