### ISSUE TITLE
I cant install in php8.1

### ISSUE THREAD

**Issue by pntrinh** [pmmp/pthreads#129]
/root/ext-pmmpthread-4.1.1/src/copy.c:296:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < num_dynamic_func_defs; i++) {
  ^

then exit.

**Comment by dktapps** [comment]
4.1.1 is outdated, and by the sound of it, so is your compiler. php-src requires a C99 compiler since PHP 8.0 or so.

**Comment by pntrinh** [comment]
ah I install newest version with this error so I tried change to 4.1.1 and it same issue
