### ISSUE TITLE
Segfault after allocating much memory in Worker task php 7.3+

### ISSUE THREAD

**Issue by alleskos** [pmmp/pthreads#3]
If you have some task which allocates memory, Worker can crash with segfault in another task. Work only if you have more than one Worker. In production, I have the task which periodically gets from DB data around 300KB and after some hours Worker crashed in another task. I wrote the example of code which usually crashing with segfault in few seconds.

```
class AllocateMemoryTask extends \Threaded {

    public function run() {
        var_dump(get_class($this));
        $justAllocateManyData = [];
        for ($i = 0; $i < 100000; $i++) {
            $justAllocateManyData[] = 'test';
        }
        $serializeData = serialize($justAllocateManyData);
        $test = [];
        for ($i = 0; $i < 100; $i++) {
            $test[] = unserialize($serializeData);
        }        
    }

}

class SimpleTask extends \Threaded {

    public function run() {
        var_dump(get_class($this));
    }

}

class MyWorker extends \Worker {

    public function run() {
        ini_set("memory_limit", -1);
    }

    public function start(int $options = PTHREADS_INHERIT_CONSTANTS) {
        parent::start($options);
    }

}

$pool = new \Pool(4, MyWorker::class);

for ($i = 0; $i < 4; $i++) {
    $pool->submit(new AllocateMemoryTask());
}

while (true) {
    for ($i = 0; $i < 4; $i++) {
        $pool->submit(new SimpleTask());
    }
    sleep(1);
}
```

**Comment by dktapps** [comment]
reproduced, will investigate.

**Comment by dktapps** [comment]
This is an interesting bug for sure. With debug-compiled PHP, this error is spammed:
```
Fatal error: Uncaught Error: Call to undefined function test() in test.php:23
Stack trace:
#0 [internal function]: SimpleTask->run()
#1 {main}
  thrown in test.php on line 23
```

**Comment by alleskos** [comment]
The problem in memory allocation when copying function. For literals memory allocated there https://github.com/pmmp/pthreads/blob/0f9f2db2037d9d8cfeec96e27dba837f36a40c23/src/copy.h#L123, for opcodes https://github.com/pmmp/pthreads/blob/0f9f2db2037d9d8cfeec96e27dba837f36a40c23/src/copy.h#L213. 
Than recalc opline->op1.constant and opline->op2.constant https://github.com/pmmp/pthreads/blob/0f9f2db2037d9d8cfeec96e27dba837f36a40c23/src/copy.h#L231-L237
If other threads allocate many memory between allocating for literals and opcodes opline->op1.constant and opline->op2.constant value may be bigger than uint32_t.
For debug I used code 
```
if (opline->op1_type == IS_CONST) {		
	uint64_t a = (zval*)(((char*)(op_array->opcodes + (opline - copy))) + (int32_t)opline->op1.constant) - literals;
	
	int64_t test = 
		(char*)(op_array->literals +
			((zval*)((char*)(op_array->opcodes + (opline - copy)) +
			(int32_t)opline->op1.constant) - literals)) -
		(char*)opline;
	opline->op1.constant = test;
	
	int64_t size_test = test > 0 ? test : -test;
	if (size_test > 0x7fffffff) {
		printf("opline->op1.constant bigger than uint32_t\n");
	}
	
	uint64_t a_new = (zval*)(((char*)(opline)) + (int32_t)opline->op1.constant) - op_array->literals;
	if (a_new != a) {
		printf("opcode error %ld %ld\n", a, a_new);
	}
}
```

**Comment by alleskos** [comment]
I tried allocate memory for literals and opcodes near but it doesn't help
```
void *literals_memory = safe_emalloc(op_array->last_literal, sizeof(zval), 0);
void *opcodes_memory = safe_emalloc(op_array->last, sizeof(zend_op), 0);
```
If allocate memory by one malloc it is help, but later when thread will join and memory try to free of course will be seg fault
```
void *literals_memory = malloc(sizeof(zval) * op_array->last_literal + sizeof(zend_op) * op_array->last);
void *opcodes_memory = literals_memory + sizeof(zval) * op_array->last_literal;
```
Maybe you have some ideas how to fix it

**Comment by dktapps** [comment]
The first thing that jumps out at me is that `znode_op.constant` is a `uint32_t`, but it's being casted to `int32_t` in the code you referenced. It's possible this is as simple as a basic "overflow" (addition of negative).

**Comment by dktapps** [comment]
This code originates from opcache as far as I recall, so if that isn't the solution, there may be answers in php-src.
