### ISSUE TITLE
Crashing tasks don't kill Worker

### ISSUE THREAD

**Issue by dktapps** [pmmp/pthreads#34]
https://github.com/krakjoe/pthreads/issues/724

Despite krakjoe's claim that this is expected behaviour, I think it's severely problematic:

- Memory issues on workers will crash all tasks that get submitted, without any indication to the main thread what's going on. This can happen due to, for example, overpopulation of thread-local storage.
- `register_shutdown_function()` is unable to capture fatal errors because it's never called (?!?!?!?!?!?)
- The parent thread has no idea that there might be a persistent state issue with a worker, causing it to continue to post tasks that subsequently fail too

One possible option is to just scrap `Worker` and reimplement it in userland (this isn't actually terribly difficult).

**Comment by SOF3** [comment]
It isn't Worker. It's just a thread that loops and waits for a sleeper notification.

Don't ask me why I didn't use Worker.

**Comment by dktapps** [comment]
Fixed by https://github.com/pmmp/ext-pmmpthread/commit/5c595c1504686e0cb6e8828fca1c752dafc85e5f.
