### ISSUE TITLE
pthreads NG

### ISSUE THREAD

**Issue by dktapps** [pmmp/pthreads#7]
PMMP has no current plans to move to parallel, but now that we're fully responsible for maintaining pthreads, a few changes need to take place to reduce the work necessary to maintain it in the future.

Some proposed changes that come to mind (not exhaustive):
- [ ] Drop environment inheritance: no class/function/constant/INI copying. Instead, require a bootstrap file (a la parallel) for autoloading. This would significantly reduce the maintenance burden, at the expense of making it impossible to support anonymous classes for `Worker` tasks and the like.
- [x] Split up `Threaded`. Its API is a mess: it currently acts as a base threadsafe class, TS map and TS queue all in one.
- [x] Get rid of the clusterfuck around `Threaded` immutability: it's confusing and really doesn't make a lot of sense, regardless of the supposed performance benefits.
- [x] Get rid of `Collectable`: it has exactly zero purpose.

**Comment by JackNoordhuis** [comment]
Could start by re-creating the repo without fork status so the code is searchable 😃

**Comment by dktapps** [comment]
yeah, I guess there's no practical value to having this repository as a fork anymore.

**Comment by dktapps** [comment]
Regarding the immutability issue: One obvious logical flaw with the jump to immutability, aside from the massive BC breaks and headaches, is that it's still slower than reading a non-threaded variable or object field.

Considering that we're already used to reading once into local vars to avoid performance hit from serialization of non-threaded vars, it's not a big stretch of the imagination to think that users would extend such semantics to reading Threaded objects for better performance (about 30% faster on non-threaded reads). Such semantics assume immutability implicitly anyway, because they read once and then don't read again.

Therefore, it seems reasonable to assume that the only unavoidable accesses to nested `Threaded` objects should be in scenarios where `Volatile` objects are needed anyway.

**Comment by dktapps** [comment]
I'm also considering scrapping `Pool` and `Worker` - both can be implemented in userland using `Thread`, which is safer and reduces the maintenance burden of the extension.

**Comment by dktapps** [comment]
A summary of changes made so far:

- Removal of `Volatile`
- Removal of `Collectable`
- `Threaded` now supports mutability a la `Volatile`, but with significantly better performance thanks to a store modcounter that's updated when `Threaded` objects are overwritten or deleted - see #15 
- Separation of `ThreadedBase` from `Threaded` - `ThreadedBase` now includes only refcounting, synchronization, and task (run, isRunning, isTerminated) APIs, while `Threaded` includes datastructure manipulation APIs (count, merge, shift, pop, chunk).
- `Thread`, `Worker` and `ThreadedSocket` now descend from `ThreadedBase` instead of `Threaded`, which eliminates the potential for idiotic bugs like [this one](https://github.com/pmmp/ClassLoader/commit/ca3912099543ddc4b4b14f40e258d84ca547dfa5).
- Removal of `Threaded::extend()` because it's fundamentally broken - see #39
