### ISSUE TITLE
pthreadVC2.dll for windows

### ISSUE THREAD

**Issue by rifkymcz** [pmmp/pthreads#70]
Where i can find the pthreadVC2.dll for windows php 8?

**Comment by dktapps** [comment]
Hi, we don't distribute standalone builds of pthreads here. It's built directly by our php-build-scripts repository. 
This fork of pthreads is maintained primarily for use by PocketMine-MP.

You could take php_pthreads and pthreadVC3.dll from these builds: https://dev.azure.com/pocketmine/PHP-Builds/_build/results?buildId=473&view=artifacts&pathAsName=false&type=publishedArtifacts
They should work with any other 8.0 ZTS x64 binary.

**Comment by rifkymcz** [comment]
Thank you sir
