### ISSUE TITLE
Unable to load dynamic library 'phtreads.so'

### ISSUE THREAD

**Issue by blocksector** [pmmp/pthreads#77]
When enabling pthreads to PHP it fails to load with the following error:

```
Unable to load dynamic library 'pthreads.so' (tried: /Users/jgauten/.phpbrew/php/php-8.0.19/lib/php/extensions/no-debug-zts-20200930/pthreads.so (dlopen(/Users/jgauten/.phpbrew/php/php-8.0.19/lib/php/extensions/no-debug-zts-20200930/pthreads.so, 0x0009): symbol not found in flat namespace '_instanceof_function')
```

Environment
==========

  * PHP: PHP 7.4.29 (cli) (built: May 31 2022 13:08:50) ( ZTS )
              Copyright (c) The PHP Group
              Zend Engine v3.4.0, Copyright (c) Zend Technologies
  * pthreads: not installed   
  * OS: MacOSX Monterey Arch: ARM

Reproducing Code
==============

- Add `extension=pthreads.so` to your default php.ini after `make install`

Expected Output
=============

pthreads should be recognized as extension or module of php, to verify I use `php -m | grep phtreads`

Actual Output
============

got this error:

```
Unable to load dynamic library 'pthreads.so' (tried: /Users/jgauten/.phpbrew/php/php-8.0.19/lib/php/extensions/no-debug-zts-20200930/pthreads.so (dlopen(/Users/jgauten/.phpbrew/php/php-8.0.19/lib/php/extensions/no-debug-zts-20200930/pthreads.so, 0x0009): symbol not found in flat namespace '_instanceof_function')
```

...and no pthreads module is loaded

**Comment by dktapps** [comment]
You can't use pthreads on a NTS binary.

**Comment by blocksector** [comment]
Sorry about that, I pasted the wrong result of php -v. we are using ZTS version of 7.4

**Comment by dktapps** [comment]
You can't mix and match extensions from different PHP versions. If you're using PHP 7.4, you need to build the extension against PHP 7.4.

**Comment by blocksector** [comment]
Hi @dktapps we did build it on 7.4.

Anyway, I tried cleaning up my machine and did a fresh install of PHP 7.4 - zts enabled, but has the same issue

**Comment by dktapps** [comment]
I'm afraid I have no idea what the problem is. It works correctly on CI which suggests you have some local issue.
