### ISSUE TITLE
Introduce ThreadedGlobals for data automatically available to all threads

### ISSUE THREAD

**Issue by dktapps** [pmmp/pthreads#80]
Currently it's not possible to provide global context to every thread unconditionally. 

There are two ways to get data from one thread to another:
1) Assign a Threaded object to a field of the Thread, and put stuff in there
2) Use class copying, and put a Threaded object in a static property of a class

Neither of these are ideal. Class copying wastes a considerable amount of CPU time and memory, and is also the largest source of bugs.

In some cases it's desirable to have something automatically available to everything, like globals, but PHP globals aren't shared between threads.

This issue proposes the introduction of the following:

```php
class ThreadedGlobals{

    public static function store(string $key, mixed $value) : void;

    public static function fetch(string $key) : mixed;
}
```

The rules on what can be stored would be identical to what Threaded object properties accept.

This would allow things like global locks to be shared. This is useful for stuff like PM's `Terminal::writeLine()`, since it would be able to guarantee synchronization without needing the class to be inherited from the main thread. For example:

```php
public static function writeLine(string $line) : void{
    $globalLock = ThreadedGlobals::fetch("stdoutLock");
    if($globalLock === null){
        $globalLock = new \Threaded();
        ThreadedGlobals::store("stdoutLock", $globalLock);
    }
    $globalLock->synchronized(fn() => echo Terminal::toANSI($line));
}
```

**Comment by sirsnyder** [comment]
I just looked at the example. `writeLine` doesn't seem thread-safe to me. Two or more threads can call the store method simultaneously for the first time. Each thread would then have its own `$globalLock` object and could perform an unsynchronized action.

**Comment by dktapps** [comment]
Yeah, that's true. I didn't think of that. Though if the global was primed in advance by a boostrap the problem wouldn't exist.
