### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by StevenProhashing** [pmmp/pthreads#81]
Fyi: PHP 8.2 has now recently been released.

**Comment by dktapps** [comment]
Duly noted, I'll probably find time to work on this over the Christmas break.

**Comment by dktapps** [comment]
Latest `fork` commits now support 8.2 (at least, all the same tests are failing on 8.2 as on 8.1). Welcome to test it and let me know what issues you find.

**Comment by scramatte** [comment]
Hi,

I've enabled phtreads on php 8.2.4  and  I've made a quick test with your basic example. I get following error:

`PHP Fatal error:  Declaration of Thread@anonymous::run() must be compatible with ThreadedRunnable::run(): void`

You must change example to append ":void" as return type for method run
```php
<?php
$thread = new class extends Thread {
	public function run():void {
		echo "Hello World\n";
	}
};

$thread->start() && $thread->join();
?>
```

**Comment by scramatte** [comment]
Hi,

Pooling example is not working. It looks that most of the examples haven't been updated to use last pthreads API.

`PHP Fatal error:  Uncaught Error: Class "Threaded" not found`

And in the examples such  CallAnyFunction.php, ChannelsAndMagic.php, ClosureFuture.php: 

`PHP Fatal error:  Uncaught Error: Cannot assign non-thread-safe value of type ... to thread-safe class property ...`

I haven't run all examples

Regards

**Comment by dktapps** [comment]
Hi, there are some API changes in v5, you may prefer to run v4.2 if you don't want to update your code. I forgot to update the examples, so most of them likely don't work anymore.

v5 has many performance and memory usage improvements, but also features an API redesign. Changelog can be seen here: https://github.com/pmmp/pthreads/releases/tag/5.0.0

**Comment by scramatte** [comment]
It would be great to update all examples. Can you update pooling example at least?

For info, I've rebuilt php 8.2.4 packages with ZTS for Debian 11 (bullseye) and I'm going to package pthreads too. 
https://debian11.nixus.es

Regards

**Comment by scramatte** [comment]
Can you tell me how to fix the following behaviour? 

`PHP Fatal error:  Uncaught Error: Cannot assign non-thread-safe value of type ... to thread-safe class property ...`

**Comment by dktapps** [comment]
you need to convert the value to something thread safe, for example by serializing it. Previous versions of pthreads did this automatically, leading to lots of confusing behaviour, so you have to do it explicitly in v5.

**Comment by dktapps** [comment]
I'm going to lock this since it doesn't really relate to PHP 8.2 support. Please write a new issue if you have further problems related to pthreads.
